name: ui
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  chopper: ^3.0.2
  provider: ^4.0.5
  json_annotation: ^3.0.1
  logging: ^0.11.4
  google_maps_flutter:
  timeline_tile:
  google_fonts:
  cupertino_icons: ^1.0.2
  
  
  flutter_localizations:
   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  chopper_generator: ^3.0.4
  json_serializable: ^3.3.0
  lite_rolling_switch: ^0.1.1
  shared_preferences: ^0.4.3
  scoped_model: ^1.0.1
 
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/map_styles/
    - assets/locale/localization_en.json
    - assets/locale/localization_es.json
  #   - images/a_dot_ham.jpeg

  
  fonts:
    - family: Jura-VariableFont
      fonts:
        - asset: assets/fonts/Jura-VariableFont_wght.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  